### ISSUE TITLE
show 3D can not work

### ISSUE THREAD

**Issue by KangchengLiu** [hailanyi/3D-Detection-Tracking-Viewer#1]
Hi,

I am testing your results but `vi.show_3D()` can not work with vedo. The `vi.show_3D()` is not complete, pls check, thanks.

**Comment by hailanyi** [comment]
Can you provide more details, such as your code or errors? it works will on my devices: Win10+Python3.6, Ubuntu 18 or 16+python3.6

**Comment by KangchengLiu** [comment]
I work with ubuntu 18.04 and python 3.6. 

The `vi.show_3D()` in your visualization code `kitti_3D_tracking_viewer.py` didn't work for me, as shown in the Figure below. The 3D Scene visualization with point clouds is blank and can not be shown. Did you upload the complete code for `show_3D()`? Thanks for your help.

![Screenshot from 2021-06-30 19-51-22](https://user-images.githubusercontent.com/37166840/123955767-9160ba00-d9dc-11eb-8b8b-96c30165885a.png)

![Screenshot from 2021-06-30 19-49-48](https://user-images.githubusercontent.com/37166840/123955601-64140c00-d9dc-11eb-9913-0f903e60e6df.png)


![Screenshot from 2021-06-30 19-42-51](https://user-images.githubusercontent.com/37166840/123954804-64f86e00-d9db-11eb-8184-767ca853c4ca.png)

**Comment by hailanyi** [comment]
Please zoom out the 3D scene by scrolling the middle mouse button backward, and then you can see the point cloud in this window.

**Comment by KangchengLiu** [comment]
Thanks for your help.
