### ISSUE TITLE
about continuous display

### ISSUE THREAD

**Issue by Typolo** [hailanyi/3D-Detection-Tracking-Viewer#5]
Hi@hailanyi , thank you for your work.i got problem in viewing a sequence data and pressing "Enter" key did not work. How can i realize continuous display as the gif in Readme.md? looking forward to your reply!

**Comment by hailanyi** [comment]
While the code is running, please first click on the 3D window and then press the "Enter" key to view a sequence data.

**Comment by Typolo** [comment]
@hailanyi,  I followed your step, it still didn't work. It seems only the 2d window could display continuous.

**Comment by zzm-hl** [comment]
I have the same problem . when the first frame is closed,the terminal shows "Process finished with exit code -1073741819 (0xC0000005)"

**Comment by zhenglianqing** [comment]
> I have the same problem . when the first frame is closed,the terminal shows "Process finished with exit code -1073741819 (0xC0000005)"

pip3 install vedo -U

**Comment by DuZzzs** [comment]
@hailanyi @Typolo  Hi, do you know how to save as a gif file? Thanks.

**Comment by hailanyi** [comment]
@DuZzzs, you can use ScreenToGif to record the 3D or 2D window.

**Comment by DuZzzs** [comment]
Thanks

**Comment by s-a-tanjim** [comment]
Set the `interactive=False` to get a continuous display. 
```python
self.vi.show( ... interactive=False ... )
```

Also to interact with continuous display make the `settings.allowInteraction` `True`.
```python
from vedo import *
settings.allowInteraction = True
```

**Comment by hailanyi** [comment]
Please use the vedo version in readme:

vedo==2021.0.6

If you can not continuous display after  press 'Enter'  please press 'Q' instead.
