### ISSUE TITLE
code reference代码引用

### ISSUE THREAD

**Issue by huahuasousou** [hailanyi/3D-Detection-Tracking-Viewer#7]
Hello, I referenced and modified your code For visualizing the dair-v2x-i dataset. This is my new project address, please check if my citations are in compliance with the specification, please let me know if you have any questions.
https://github.com/huahuasousou/dair_v2x_i_dataset_vis

你好，我引用并修改了你的代码用于可视化dair-v2x-i dataset。这是我的新项目地址，请你检查我的引用是否符合规范，如果有任何问题欢迎告诉我。
https://github.com/huahuasousou/dair_v2x_i_dataset_vis

**Comment by hailanyi** [comment]
没事哈，随便用，谢谢引用 ：）
