### ISSUE TITLE
Pcdet检测结果显示异常

### ISSUE THREAD

**Issue by OPPOA113** [hailanyi/3D-Detection-Tracking-Viewer#9]
你好。感谢开源这么好的code。
我在可视化Pcdet PVRCNN的检测结果时，显示如下的异常。麻烦看下是何原因。谢谢
pvrcnn的结果，在pcdet的工程下可视化是正常的。但是在本工程下就有这样的问题。。
![Snipaste_2022-05-16_15-38-09](https://user-images.githubusercontent.com/4974108/168543570-1d39cb95-24bb-4daf-9b92-a6f4d46c5182.jpg)

pvcnn输出结果，如下：
![Snipaste_2022-05-16_15-38-52](https://user-images.githubusercontent.com/4974108/168543621-12e8709f-5133-426a-9216-b69f5244afed.jpg)

**Comment by hailanyi** [comment]
你好，如果从label_02读入box，则需要先将OpenPCDet的格式转为KITTI的格式。OpenPCDet输出的result.pkl中保存了在相机坐标系下的location和dimension，可以按KITTI的格式存为txt。请注意KITTI的长宽高和OpenPCDet中长宽高的顺序不一样。

**Comment by JulyLi2019** [comment]
> 你好。感谢开源这么好的code。 我在可视化Pcdet PVRCNN的检测结果时，显示如下的异常。麻烦看下是何原因。谢谢 pvrcnn的结果，在pcdet的工程下可视化是正常的。但是在本工程下就有这样的问题。。 ![Snipaste_2022-05-16_15-38-09](https://user-images.githubusercontent.com/4974108/168543570-1d39cb95-24bb-4daf-9b92-a6f4d46c5182.jpg)
> 
> pvcnn输出结果，如下： ![Snipaste_2022-05-16_15-38-52](https://user-images.githubusercontent.com/4974108/168543621-12e8709f-5133-426a-9216-b69f5244afed.jpg)

你好，我也是希望通过Pcdet完成可视化，您的代码可以给我做个参考吗？
